name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: CGO_ENABLED=0 go build -o zinc cmd/zinc/main.go

    - name: Test
      run: ./coverage.sh

    - name: Codecov
      uses: codecov/codecov-action@v3.1.0
